stages:
  - build
  - publish

variables:
  PYTHON_VERSION: "3.13"
  UV_VERSION: "0.5.5"
  UV_PUBLISH_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
  UV_PUBLISH_USERNAME: "gitlab-ci-token"
  UV_PUBLISH_PASSWORD: "${CI_JOB_TOKEN}"

#before_script:
#  - pip install uv==$UV_VERSION

build:
  stage: build
  tags:
    - nix
  script:
    - nix --extra-experimental-features "nix-command flakes" develop -c uv build
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  script:
    - nix --extra-experimental-features "nix-command flakes" develop -c uv publish --publish-url $UV_PUBLISH_URL dist/*
  #only:
  #  - tags

